FROM centos:6

RUN yum install -y make rpmdevtools

RUN mkdir -p /root/rpmbuild/{BUILD,RPMS,SOURCES,SPECS,SRPMS}
RUN sed -i "s;%_build_name_fmt.*;%_build_name_fmt\t%%{ARCH}/%%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.el6.rpm;" /usr/lib/rpm/macros

RUN mkdir /vaz
WORKDIR /vaz
