#!/bin/sh

set -e

case "$1" in

  configure)
    update-rc.d vaz defaults
    update-rc.d vaz enable >/dev/null 2>&1
  ;;

  abort-upgrade|abort-remove|abort-deconfigure)
    exit 0
  ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
  ;;
esac
